parameters:
#    ourss_install.example.class: Ourss\InstallBundle\Example

services:
#    ourss_install.example:
#        class: %ourss_install.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
